name = "Wordpress Twenty Twenty Hugo"
license = "MIT"
licenselink = "https://github.com/themefisher/wordpress-twenty-twenty-hugo/blob/master/LICENSE"
description = "Hugo port of the Themefisher’s Parsa Template"
homepage = "https://gethugothemes.com/products/wordpress-twenty-twenty/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'wordpress', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['wordpress','responsive']
min_version = "0.62.2"

[author]
  name = "Themefisher"
  homepage = "https://themefisher.com/"